const THREE_DIGISTS = 3;
const PLAYER_INPUT_SENTENCE = "숫자를 입력해주세요 : ";
const GAME_START_SENTENCE = "숫자 야구 게임을 시작합니다.";

exports.THREE_DIGISTS = THREE_DIGISTS;
exports.PLAYER_INPUT_SENTENCE = PLAYER_INPUT_SENTENCE;
exports.GAME_START_SENTENCE = GAME_START_SENTENCE;
